version: '3'
services: 
  coap-calculator:
    build: ./things/coap/js/calculator/
    ports:
      - "5683:5683/udp"
  http-express-calculator:
    build: ./things/http/express/calculator/
    ports:
      - "3000:3000"
  http-flask-calculator:
    build: ./things/http/flask/calculator/
    ports:
      - "5000:5000"
  mqtt-calculator:
    build: ./things/mqtt/js/calculator/
    ports:
      - "1883:1883"